# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Docker Image for Tempo

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push the image
    - uses: actions/checkout@v3
    - run:
       docker login --username bolasto --password ${{ secrets.TEMPO_PY }}
       docker build . --tag ghcr.io/bolasto/tempoapp:latest
       docker push ghcr.io/bolasto/tempoapp:latest
